apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: z9m9p4ehs-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/z9m9p4ehs-java-quarkus-gitops